### ISSUE TITLE
I can't get docker miele-to-mqtt-gw to work

### ISSUE THREAD

**Issue by cvc90** [mqtt-home/miele-to-mqtt-gw#106]
Hello, could you help me to get  [miele-to-mqtt-gw](https://github.com/mqtt-home/miele-to-mqtt-gw)? For some reason I can't get the Docker version to work, it doesn't get the token to work and looking at the log it gives me a 401 error (invalid credentials) and that's why it doesn't receive the token (I attach an image showing what I'm saying).

![image](https://github.com/mqtt-home/miele-to-mqtt-gw/assets/76731844/0edf296e-d3d5-4070-9687-a27147b41a8d)
![image](https://github.com/mqtt-home/miele-to-mqtt-gw/assets/76731844/addbcf6d-265e-40fb-9c17-8961e8fc7525)

The configuration is the same as [config-example.json]( https://github.com/mqtt-home/miele-to-mqtt-gw/blob/main/config-example.json) but changing client-id, client -secret, username, password and I checked the credentials both on the page and in the miele app and I can say that it works correctly.

From the page https://www.miele.com/developer/swagger-ui/swagger.html everything seems to work correctly and I can see my devices without problems.

![image](https://github.com/mqtt-home/miele-to-mqtt-gw/assets/76731844/2a0d1cdc-69db-44cc-b65e-8a60c731becd)

Could it be that today [miele-to-mqtt-gw](https://github.com/mqtt-home/miele-to-mqtt-gw) doesn't work?
or the credentials written in the .json file containing special characters do not read them correctly?

**Comment by AleksCee** [comment]
Hi @cvc90 in my log are errors since 1 am today but I have just restart the container and it‘s seams to work right now:

16:33:02.609 INFO  - Info enabled
16:33:02.627 INFO  - Connecting MQTT client
16:33:04.159 INFO  - MQTT client connected
16:33:06.582 INFO  - Using Miele polling api

Alex

**Comment by philipparndt** [comment]
@cvc90 which version do you use? Do you like to test `pharndt/mielemqtt:3.0.0-pre`?

my full config.json:
```json
{
  "mqtt": {
    "url": "tcp://mosquitto:1883",
    "retain": true,
    "topic": "home/miele",
    "qos": 2,
    "bridge-info": true,
    "autoPublish": true,
    "deduplicate": true
  },
  "miele": {
    "client-id": "12345678-abcd-1234-1234-123456789abc",
    "client-secret": "01234567890123456789012345678901",
    "username": "some@other.de",
    "password": "password",
    "mode": "sse",
    "polling-interval": 30,
    "token": {
      "access": "DE_5c...",
      "refresh": "DE_f6...",
      "validUntil": "2022-08-30T11:32:40.434+02:00[Europe/Berlin]"
    }
  }
}
```

my docker-compose.yml snipped
```yml
  ...
  mielemqtt:
    environment:
      TZ: "Europe/Berlin"
    hostname: mielemqtt
    image: pharndt/mielemqtt:3.0.0-pre
    volumes:
      - ./config/miele:/var/lib/miele-to-mqtt-gw:rw
    restart: always
    depends_on:
      - mosquitto
    cpus: 0.1
    mem_reservation: "50M"
    mem_limit: "50M"
  ...
```
